const fs = require('fs');
const code = [
"const { getDb } = require('../config/database');",
"const { v4: uuidv4 } = require('uuid');",
"const generateRoadmapWithAI = async (subject, lastCourse, subjectsStudied, timeHours) => {",
"  const apiKey = process.env.GROQ_API_KEY;",
"  if (!apiKey) throw new Error('GROQ_API_KEY not set in backend/.env');",
"  const promptText = 'You are an expert curriculum designer. Generate a learning roadmap for: ' + subject + '. Last course: ' + (lastCourse || 'Not specified') + '. Previous subjects: ' + (subjectsStudied || 'Not specified') + '. Available time: ' + timeHours + ' hours. Return ONLY valid JSON no markdown no explanation: {\"title\":\"string\",\"description\":\"string\",\"prerequisites\":\"string\",\"modules\":[{\"title\":\"string\",\"level\":\"beginner\",\"elapsed_hours\":2,\"topics\":[\"topic1\",\"topic2\"],\"youtube_query\":\"search terms\"}]} Rules: level = beginner or intermediate or advanced. elapsed_hours sum = ' + timeHours + '. Include 4 to 8 modules.';",
"  const response = await fetch('https://api.groq.com/openai/v1/chat/completions', {",
"    method: 'POST',",
"    headers: { 'Content-Type': 'application/json', 'Authorization': 'Bearer ' + apiKey },",
"    body: JSON.stringify({ model: 'llama3-8b-8192', messages: [{ role: 'user', content: promptText }], max_tokens: 2048, temperature: 0.7 })",
"  });",
"  if (!response.ok) { const text = await response.text(); throw new Error('Groq error ' + response.status + ': ' + text); }",
"  const data = await response.json();",
"  if (!data.choices || !data.choices[0]) throw new Error('No response from Groq');",
"  const raw = data.choices[0].message.content.trim().replace(/```json/g, '').replace(/```/g, '').trim();",
"  console.log('Roadmap generated using Groq llama3');",
"  return JSON.parse(raw);",
"};",
"const createRoadmap = async (req, res) => {",
"  const subject = req.body.subject;",
"  const last_course = req.body.last_course;",
"  const subjects_studied = req.body.subjects_studied;",
"  const time_hours = req.body.time_hours;",
"  if (!subject) return res.status(400).json({ message: 'subject is required.' });",
"  const hours = parseInt(time_hours) || 10;",
"  try {",
"    const data = await generateRoadmapWithAI(subject, last_course, subjects_studied, hours);",
"    const db = getDb();",
"    const id = uuidv4();",
"    db.prepare('INSERT INTO roadmaps (id,user_id,subject,last_course,subjects_studied,time_hours,title,description,prerequisites,modules) VALUES (?,?,?,?,?,?,?,?,?,?)').run(id, req.user.id, subject, last_course || '', subjects_studied || '', hours, data.title, data.description, data.prerequisites, JSON.stringify(data.modules));",
"    db.prepare('INSERT INTO activity_log (id,user_id,action,description) VALUES (?,?,?,?)').run(uuidv4(), req.user.id, 'ROADMAP_GENERATED', 'Generated: ' + subject);",
"    res.status(201).json({ message: 'Roadmap generated.', roadmap: { id: id, title: data.title, description: data.description, prerequisites: data.prerequisites, modules: data.modules, subject: subject, time_hours: hours, created_at: new Date().toISOString() } });",
"  } catch (err) {",
"    console.error('Roadmap generation error:', err.message);",
"    res.status(500).json({ message: 'Failed to generate roadmap.', error: err.message });",
"  }",
"};",
"const getMyRoadmaps = (req, res) => {",
"  const rows = getDb().prepare('SELECT * FROM roadmaps WHERE user_id=? ORDER BY created_at DESC').all(req.user.id);",
"  res.json({ roadmaps: rows.map(function(r) { return Object.assign({}, r, { modules: JSON.parse(r.modules || '[]') }); }) });",
"};",
"const getRoadmapById = (req, res) => {",
"  const db = getDb();",
"  const roadmap = db.prepare('SELECT * FROM roadmaps WHERE id=?').get(req.params.id);",
"  if (!roadmap) return res.status(404).json({ message: 'Roadmap not found.' });",
"  if (roadmap.user_id !== req.user.id && req.user.role !== 'teacher') return res.status(403).json({ message: 'Access denied.' });",
"  const progress = db.prepare('SELECT * FROM roadmap_progress WHERE roadmap_id=?').all(req.params.id);",
"  res.json({ roadmap: Object.assign({}, roadmap, { modules: JSON.parse(roadmap.modules || '[]') }), progress: progress });",
"};",
"const updateProgress = (req, res) => {",
"  const module_index = req.body.module_index;",
"  const completed = req.body.completed;",
"  const db = getDb();",
"  const roadmap = db.prepare('SELECT * FROM roadmaps WHERE id=?').get(req.params.id);",
"  if (!roadmap || roadmap.user_id !== req.user.id) return res.status(404).json({ message: 'Not found.' });",
"  const existing = db.prepare('SELECT id FROM roadmap_progress WHERE roadmap_id=? AND user_id=? AND module_index=?').get(req.params.id, req.user.id, module_index);",
"  const val = completed ? 1 : 0;",
"  const ts = completed ? new Date().toISOString() : null;",
"  if (existing) { db.prepare('UPDATE roadmap_progress SET completed=?,completed_at=? WHERE id=?').run(val, ts, existing.id); }",
"  else { db.prepare('INSERT INTO roadmap_progress (id,roadmap_id,user_id,module_index,completed,completed_at) VALUES (?,?,?,?,?,?)').run(uuidv4(), req.params.id, req.user.id, module_index, val, ts); }",
"  res.json({ message: 'Progress updated.' });",
"};",
"const deleteRoadmap = (req, res) => {",
"  const db = getDb();",
"  const roadmap = db.prepare('SELECT * FROM roadmaps WHERE id=?').get(req.params.id);",
"  if (!roadmap || roadmap.user_id !== req.user.id) return res.status(404).json({ message: 'Not found.' });",
"  db.prepare('DELETE FROM roadmaps WHERE id=?').run(req.params.id);",
"  res.json({ message: 'Deleted.' });",
"};",
"module.exports = { createRoadmap, getMyRoadmaps, getRoadmapById, updateProgress, deleteRoadmap };"
].join('\n');
fs.writeFileSync('controllers/roadmapController.js', code);
console.log('SUCCESS!');